# -*- coding: utf-8 -*-
"""homework_api_demon_slayer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1epgUaDAq0_P2WH74lRmKpYuPhhHKu3pE

#ดึงข้อมูลจาก public API มาสร้าง dataframe

ดึงข้อมูลตัวละครจากเรื่อง Demon Slayer: Kimetsu no Yaiba

Documentation: https://www.demonslayer-api.com/documentation

Endpoint: https://www.demonslayer-api.com/api/v1/characters?id={id}
"""

import requests

## api endpoint
url = "https://www.demonslayer-api.com/api/v1/characters?id=1"

requests.get(url)

"""ฝากค่าที่ได้จาก endpoint ของตัวละคร id ที่ 1 ไว้ในชื่อ response
แล้วใช้ function json เรียกดูข้อมูล
"""

response = requests.get(url)

response.json()

response.json()['content'][0]['name']

response.json()['content'][0]['age']

response.json()['content'][0]['quote']

response.json()['content'][0]['affiliation']['name']

response.json()['content'][0]['combat_style'][0]['name']

"""##for loop

ดึงข้อมูลทีละหลายคนต้องใช้ for loop

index เริ่มจาก 0 เลข id จึงต้องเป็น i+1
"""

import requests
import time

characters = []

for i in range(45):
    url = f"https://www.demonslayer-api.com/api/v1/characters?id={i+1}"
    try:
        response = requests.get(url)
        response_json = response.json()
        data = [response_json['content'][0]['name'],
                response_json['content'][0]['age'],
                response_json['content'][0]['affiliation']['name'],
                response_json['content'][0]['combat_style'][0]['name']]
        characters.append(data)
        print(f"Success: {i+1}")
        time.sleep(1)
    except:
        print("No character data found.")

"""แต่วิธีด้านบนนี้ทำให้ตัวละคร id 27 และ 42 ถูกข้ามไป ไม่ได้เก็บข้อมูลมา"""

print(characters)

"""แก้ต่อโดยเพิ่ม if else และใช้ .get method"""

import requests
import time

characters = []

for i in range(45):
    url = f"https://www.demonslayer-api.com/api/v1/characters?id={i+1}"

    try:
        response = requests.get(url)
        response_json = response.json()
        content = response_json.get('content', [])
        char = content[0]

        combat_styles = char.get('combat_style', [])
        combat_name = combat_styles[0].get('name', 'None') if combat_styles else "None"

        data = [char.get('name', 'Unknown'),
                char.get('age', 'Unknown'),
                char.get('gender', 'Unknown'),
                char.get('race', 'Unknown'),
                char.get('affiliation', {}).get('name', 'None'),
                combat_name]

        characters.append(data)
        print(f"Success: {i+1}")

    except:
        print(f"Error on ID {i+1}")

    time.sleep(1)

print(characters)

import pandas as pd

demonslayer = pd.DataFrame(characters,
              columns = ["name",
                         "age",
                         "gender",
                         "race",
                         "affiliation",
                         "combat style"])

demonslayer